# MBedwars Kits Addon
Prefix: "&c&lK&a&lI&e&lT &7>"

Features:
  Enabled: true
  # Set it to true on the server with bungee/proxy sync (It won't save kits from there)
  Game_server: false
  # Enables per kit perms kitsaddon.<id>
  Per_kit_perm: false
  Blocked_arenas: []
Menu:
  Title: "&a&lK&c&lI&6&lT&7s"
# Messages
Messages:
  # PLAYER PLACEHOLDERS WORKS
  # %kit_name% => returns the kit (if available), %kit_id% => returns kit's id
  Kit_No_permission: "&c&lSorry %player_name%! &7you haven't unlocked the kit yet."
  Kit_already_selected: "&c&lSorry %player_name%! &7you have already selected %kit_name%."
  Kit_selected: "&a&lYay %player_name%! &7You have now selected %kit_name% kit."


# you can create custom aliases from here.
Command_alias: ["kits", "kit", "mbwkits"]