# MBedwars Kits Addon
Prefix: "&c&lK&a&lI&e&lT &7>"

Features:
  Enabled: true
  # Set it to true on every backend server with bungee/proxy sync (It won't save kits from there)
  # Only set it to false on the main hub server/s
  Game_server: false
  # Enables per kit perms kitsaddon.<id>
  Per_kit_perm: false
  # decreasing it significantly may cause troubles with other plugins (in seconds)
  Give_kit_delay: 5
  # Enabling it alloys players to get kit on respawn.
  Give_kit_on_respawn: false
  Blocked_arenas: ["YourFavBlockedArena"]

# Currently menu is limited to one page only.
Menu:
  # %page_total% : returns total number of pages
  # %page_current% : returns current page
  Title: "&a&lK&c&lI&6&lT&7s &7(%page_current%/%page_total%)"
  Previous_page:
    Name: "&cPrevious page"
    Description:
      - ""
      - "&7Click to go back to previous page"
  Next_page:
    Name: "&aNext Page"
    Description:
      - ""
      - "&7Click to go to the next page"
  Player_head:
    Name: "%player_name%'&7s info"
    Description:
      - ""
      - "&eSelected kit: %mbw-kit_current%"
# Messages
Messages:
  # PLAYER PLACEHOLDERS WORKS
  # %kit_name% => returns the kit (if available), %kit_id% => returns kit's id
  Kit_No_permission: ["&c&lSorry %player_name%! &7you haven't unlocked the kit yet."]
  Kit_already_selected: ["&c&lSorry %player_name%! &7you have already selected %kit_name%."]
  Kit_already_exists: ["&c&lSorry %player_name%! &7%kit_name% kit already exists with that id."]
  Kit_does_not_exists: ["&c&lSorry %player_name%! &7%kit_name% does not exists with that id."]
  Kit_created: ["&a&lYAY! &7%kit_name% with the id %kit_id% has been created!!."]
  Kit_removed: ["&a&lYAY! &7%kit_name% with the id %kit_id% has been removed."]
  Kit_selected: ["&a&lYay %player_name%! &7You have now selected %kit_name% kit."]
  Kit_icon_edited: ["&a&lYay %player_name%! &7You have updated the &6%kit_name%."]
  Kit_given: ["&aYou got %kit_name% kit!"]
  Kit_saved: ["&aYou have saved all the loaded kits into &6kits.yml!"]
  Kit_loaded: ["&aYou have loaded all the kits from &6kits.yml!"]
  Command_invalid: ["&c&lINVALID &ccommand usage!"]
  Command_invalid_material: ["&c&lINVALID &cPlease use existing material name."]
  # Returns on /kit
  Command_help:
    - ""
    - " &6&lMBedwars Kits Addon by Harshu"
    - ""
    - "  &7Allows you to create and use custom kits in"
    - "  &7Bedwars, you can also use the following commands:-"
    - "[CUSTOM COMMAND GUIDE HERE]"
